// <auto-generated />
using System;
using Iqamah.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Iqamah.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611094000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Iqamah.Domain.Entities.PrayerLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsJamaah")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsJummah")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsOffered")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTraveling")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MissedReason")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PrayerDate")
                        .HasColumnType("date");

                    b.Property<int>("PrayerName")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("WaqtStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PrayerDate");

                    b.HasIndex("UserId", "PrayerName", "PrayerDate")
                        .IsUnique();

                    b.ToTable("PrayerLogs", (string)null);
                });

            modelBuilder.Entity("Iqamah.Domain.Entities.QazaLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FulfilledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("OriginalPrayerDate")
                        .HasColumnType("date");

                    b.Property<Guid>("PrayerLogId")
                        .HasColumnType("uuid");

                    b.Property<int>("PrayerName")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("TimeToResolution")
                        .HasColumnType("interval");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PrayerLogId")
                        .IsUnique();

                    b.HasIndex("UserId", "State");

                    b.HasIndex("UserId", "PrayerName", "State");

                    b.ToTable("QazaLogs", (string)null);
                });

            modelBuilder.Entity("Iqamah.Domain.Entities.QazaLog", b =>
                {
                    b.HasOne("Iqamah.Domain.Entities.PrayerLog", "PrayerLog")
                        .WithOne("QazaLog")
                        .HasForeignKey("Iqamah.Domain.Entities.QazaLog", "PrayerLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrayerLog");
                });

            modelBuilder.Entity("Iqamah.Domain.Entities.PrayerLog", b =>
                {
                    b.Navigation("QazaLog");
                });
#pragma warning restore 612, 618
        }
    }
}
